server:
  port: 9098    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: school-service    #service name
  cloud:
    config:
      uri: http://localhost:8888

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,refresh

logging:
  level:
    org.hzhang: DEBUG